rmrk-team/evm

test/evm-resource-test-simple.ts
Refactors tests to make each more specific and reuse code.
Adds missing tests related to permissions.
=> Test improvements on resource tests

contracts/RMRK/RMRKMultiResource.sol, test/evm-resource-test-simple.ts
Also adds control of max pending resources and its test.
=> Tests events emitted from resources

contracts/RMRK/RMRKCore.sol, contracts/RMRK/RMRKNesting.sol, contracts/RMRK/interfaces/IRMRKCore.sol, contracts/RMRK/interfaces/IRMRKNestingInternal.sol, test/evm-nesting-test-simple.ts
There are a few FIXMES pending but I'd like to merge this already mainly to avoid future conflicts.
=> Transfer from child

contracts/RMRK/RMRKEquippable.sol, contracts/RMRK/RMRKNestingMultiResource.sol, contracts/RMRK/abstracts/MultiResourceAbstract.sol, contracts/RMRK/abstracts/MultiResourceAbstractBase.sol, contracts/RMRK/interfaces/IMultiResource.sol, contracts/RMRK/interfaces/IRMRKEquippableResource.sol, contracts/RMRK/interfaces/IRMRKMultiResourceBase.sol, test/multiresource.ts
This includes events, all internal variables except for resources and all functions which do not require access to resources, since structs are different in both implementations.
=> Refactors all common from MultiResource and Equippables

contracts/RMRK/RMRKMultiResource.sol, contracts/RMRK/abstracts/ERC721Abstract.sol, contracts/RMRK/abstracts/MultiResourceAbstract.sol, contracts/mocks/RMRKEquippableMock.sol, contracts/mocks/RMRKNestingMultiResourceMock.sol
Converted more require strings to custom errors
=> Update multi resource custom errors

contracts/RMRK/RMRKBaseStorage.sol, contracts/mocks/RMRKBaseStorageMock.sol, test/baseStorage.ts, yarn.lock
I have added more tests for the RMRKBaseStorage contract.
Everything seems fine except the checkIsEquippableMulti function which doesn't work as expected, I tried to debug it but couldn't find any logical reason why it returns an array out of bounds error.
=> Add base storage tests

contracts/implementations/RMRKEquippableImpl.sol, contracts/implementations/RMRKMultiResourceImpl.sol, contracts/implementations/RMRKNestingExternalEquipImpl.sol, contracts/implementations/RMRKNestingImpl.sol, contracts/implementations/RMRKNestingMultiResourceImpl.sol, scripts/deploy_islands.ts, scripts/deploy_multiresource.ts, scripts/deploy_nesting.ts, test/behavior/multiresource.ts, test/implementations/equippable.ts, test/implementations/externalEquippable.ts, test/implementations/multiresource.ts, test/implementations/nesting.ts, test/implementations/nestingMultiResource.ts
The tokenURI is just one for all the collection and it's set on deploy since it's expected to be used only as a fallback and to have compatibility with other marketplaces. 
The resources are expected to be loaded from multi resource implementation.
=> Receives tokenURI on deploy for all implementations.

contracts/RMRK/base/IRMRKBaseStorage.sol, contracts/RMRK/base/RMRKBaseStorage.sol, contracts/implementations/RMRKBaseStorageImpl.sol, contracts/mocks/RMRKBaseStorageMock.sol, test/baseStorage.ts, test/behavior/baseStorage.ts, test/implementations/baseStorage.ts
Moves struct to interface
Removes symbol
Adds metadataURI
Adds getType and getMetadataURI to interface.
=> Changes on RMRKBaseStorage

contracts/RMRK/access/OwnableLock.sol, contracts/implementations/RMRKBaseStorageImpl.sol, contracts/implementations/RMRKEquippableImpl.sol, contracts/implementations/RMRKExternalEquipImpl.sol, contracts/implementations/RMRKMultiResourceImpl.sol, contracts/implementations/RMRKNestingExternalEquipImpl.sol, contracts/implementations/RMRKNestingMultiResourceImpl.sol
Issuer can add/revoke contributors which are allowed to manage resources, parts and other admin only operations.
=> Adds Contributor concept

contracts/RMRK/equippable/RMRKEquippable.sol, contracts/RMRK/equippable/RMRKNestingExternalEquip.sol, contracts/RMRK/nesting/IRMRKNesting.sol, contracts/RMRK/nesting/RMRKNesting.sol, test/behavior/equippableSlots.ts, test/behavior/nesting.ts, test/extensions/soulbound.ts, test/extensions/typedMultiResource.ts, test/utils.ts
Allows to unnest a pending child.
Merges reject child into unnest (pending) child.
=> Unnest pending

contracts/RMRK/nesting/RMRKNesting.sol, contracts/mocks/RMRKNestingMock.sol, test/nesting.ts
Adds nesting hooks and some questions about missing restrictions.
=> Nested hooks

contracts/RMRK/core/RMRKCore.sol, contracts/RMRK/extension/RMRKRoyalties.sol, package.json
For the marketplace frontend it's useful to have a simple getter for royalty percentage fee.
=> Add royalty percentage public function

contracts/RMRK/equippable/RMRKEquippable.sol, contracts/RMRK/equippable/RMRKExternalEquip.sol, contracts/RMRK/equippable/RMRKNestingExternalEquip.sol, contracts/RMRK/extension/reclaimableChild/RMRKReclaimableChild.sol, contracts/RMRK/nesting/RMRKNesting.sol
This allows custom implementers to by pass gating under certain conditions as
- Minting
- Factories
- Game Contracts
=> Splits all management operations into a gated and an internal version

contracts/security_mocks/ChildAdder.sol, docs/security_mocks/ChildAdder.md
NatSpec comments have been added to the ChildAdder smart contract.
=> Document ChildAdder smart contract with NatSpec

contracts/RMRK/utils/IERC20.sol, contracts/RMRK/utils/RMRKCollectionMetadata.sol, contracts/RMRK/utils/RMRKEquipRenderUtils.sol, contracts/RMRK/utils/RMRKMintingUtils.sol, contracts/RMRK/utils/RMRKMultiResourceRenderUtils.sol, docs/RMRK/utils/IERC20.md, docs/RMRK/utils/RMRKCollectionMetadata.md, docs/RMRK/utils/RMRKEquipRenderUtils.md, docs/RMRK/utils/RMRKMintingUtils.md, docs/RMRK/utils/RMRKMultiResourceRenderUtils.md
NatSpec comments have been added to the utils smart contracts, the existing ones updated and some reclassified.
A typo discovered in the `RMRKEquipRenderUtils` smart contract has been fixed as well.
=> Fully document utils smart contracts with NatSpec

contracts/RMRK/multiasset/AbstractMultiAsset.sol, contracts/implementations/RMRKExternalEquipImpl.sol, contracts/implementations/abstracts/RMRKAbstractEquippableImpl.sol, contracts/implementations/abstracts/RMRKAbstractMultiAssetImpl.sol, contracts/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.sol, test/implementations/equippable.ts, test/implementations/externalEquippable.ts, test/implementations/multiasset.ts, test/implementations/nestableMultiasset.ts
Also removes legacy code on test.
=> Auto accepts assets on tokens when sender is token owner

contracts/implementations/abstracts/RMRKAbstractMultiAssetImpl.sol, docs/implementations/RMRKMultiAssetImpl.md, docs/implementations/abstracts/RMRKAbstractMultiAssetImpl.md, docs/implementations/erc20Pay/RMRKMultiAssetImplErc20Pay.md
This was the only implementation without an exposed burn method
=> Adds public burn on multiasset implementations.

.eslintrc.js, package.json, test/equippable.ts, test/extensions/nestableAutoIndex.ts, test/extensions/reclaimableChild.ts, test/extensions/soulbound.ts, test/externalEquip.ts, test/implementations/equippable.ts, test/implementations/erc20pay.ts, test/implementations/externalEquippable.ts, test/implementations/multiasset.ts, test/implementations/nestableMultiasset.ts, test/mintingUtils.ts, test/nestableExternalEquip.ts, test/nestableMultiasset.ts, test/nestableSecTests.ts, test/renderUtils.ts, tsconfig.json, yarn.lock
Updated configs for ts/eslint
Added type safety to contracts where appropriate
=> Add type safety to contract fields

contracts/RMRK/access/Ownable.sol, contracts/RMRK/access/OwnableLock.sol, contracts/RMRK/utils/RMRKMintingUtils.sol, contracts/mocks/MintingUtilsMock.sol, test/mintingUtils.ts
Adds missing coverage on minting utils and fixes 2 bugs.
=> Fixes max supply to total supply when contract is locked

contracts/RMRK/access/OwnableLock.sol, contracts/implementations/RMRKEquippableImpl.sol, contracts/implementations/RMRKMultiAssetImpl.sol, contracts/implementations/RMRKNestableExternalEquipImpl.sol, contracts/implementations/RMRKNestableImpl.sol, contracts/implementations/RMRKNestableMultiAssetImpl.sol, contracts/implementations/abstracts/RMRKAbstractEquippableImpl.sol, contracts/implementations/abstracts/RMRKAbstractMultiAssetImpl.sol, contracts/implementations/abstracts/RMRKAbstractNestableImpl.sol, contracts/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.sol, contracts/implementations/erc20Pay/RMRKEquippableImplErc20Pay.sol, contracts/implementations/erc20Pay/RMRKMultiAssetImplErc20Pay.sol, contracts/implementations/erc20Pay/RMRKNestableImplErc20Pay.sol, contracts/implementations/erc20Pay/RMRKNestableMultiAssetImplErc20Pay.sol, contracts/implementations/premint/RMRKEquippableImplPreMint.sol, contracts/implementations/premint/RMRKMultiAssetImplPreMint.sol, contracts/implementations/premint/RMRKNestableImplPreMint.sol, contracts/implementations/premint/RMRKNestableMultiAssetImplPreMint.sol, docs/implementations/erc20Pay/RMRKEquippableImplErc20Pay.md, docs/implementations/erc20Pay/RMRKNestableMultiAssetImplErc20Pay.md, docs/implementations/premint/RMRKEquippableImplPreMint.md, docs/implementations/premint/RMRKMultiAssetImplPreMint.md, docs/implementations/premint/RMRKNestableImplPreMint.md, docs/implementations/premint/RMRKNestableMultiAssetImplPreMint.md, test/implementations/erc20pay.ts, test/implementations/premint.ts
On pre minting implementations, only owner can mint and there's no cost.
Moves IRMRKInitData import to abstract on implementations.
Removes redundant modifier and improves coverage.
=> Adss implementations with pre minting strategy and other improvements

contracts/RMRK/base/RMRKBaseStorage.sol
I found this code when I view it. But I don't think it needed to check if length of array is less than 0
=> change compare condition from less or equal 0 to equal 0

contracts/implementations/RMRKExternalEquipImpl.sol, contracts/implementations/abstracts/RMRKAbstractEquippableImpl.sol, contracts/mocks/RMRKEquippableMock.sol, contracts/mocks/RMRKExternalEquipMock.sol, docs/implementations/RMRKEquippableImpl.md, docs/implementations/RMRKExternalEquipImpl.md, docs/implementations/abstracts/RMRKAbstractEquippableImpl.md, docs/implementations/erc20Pay/RMRKEquippableImplErc20Pay.md, docs/implementations/premint/RMRKEquippableImplPreMint.md, docs/mocks/RMRKEquippableMock.md, docs/mocks/RMRKExternalEquipMock.md, docs/mocks/extensions/soulbound/RMRKSoulboundEquippableMock.md, docs/mocks/extensions/typedMultiAsset/RMRKTypedEquippableMock.md, docs/mocks/extensions/typedMultiAsset/RMRKTypedExternalEquippableMock.md, test/behavior/equippableAssets.ts, test/behavior/equippableParts.ts, test/implementations/equippable.ts, test/implementations/externalEquippable.ts, test/renderUtils.ts, test/setup/equippableParts.ts, test/setup/equippableSlots.ts, test/utils.ts
Also makes available the function to add regular assets.
=> Uses a different function to add equippable assets

hardhat.config.ts, package.json
Added dodoc config, so that the documentation is regenerated every time the contracts are compiled.
=> Regenerate docs on compile

LICENSE, NOTICE.md, contracts/RMRK/core/RMRKCore.sol, contracts/RMRK/library/RMRKErrors.sol, contracts/RMRK/utils/RMRKEquipRenderUtils.sol, contracts/RMRK/utils/RMRKMultiAssetRenderUtils.sol, contracts/RMRK/utils/RMRKNestableRenderUtils.sol, contracts/RMRK/utils/RMRKRenderUtils.sol, docs/RMRK/utils/RMRKEquipRenderUtils.md, docs/RMRK/utils/RMRKMultiAssetRenderUtils.md, docs/RMRK/utils/RMRKNestableRenderUtils.md, docs/RMRK/utils/RMRKRenderUtils.md, package.json, scripts/deploy_renderUtils.ts, test/behavior/equippableParts.ts, test/behavior/equippableSlots.ts, test/renderUtils.ts
Merge dev into master after releasing v0.24.1.
=> Bumps version to v0.24.1

contracts/RMRK/core/RMRKCore.sol, contracts/RMRK/utils/RMRKEquipRenderUtils.sol, package.json, scripts/generate_abis.ts
This syncs dev with master after releasing `v0.24.2`.
=> Bumps version to v0.24.2

contracts/RMRK/core/RMRKCore.sol, package.json
Sync master with dev after releasing `v0.27.1`.
=> Bump version to v0.27.1

contracts/RMRK/utils/RMRKEquipRenderUtils.sol, contracts/RMRK/utils/RMRKMultiAssetRenderUtils.sol, contracts/RMRK/utils/RMRKNestableRenderUtils.sol, docs/RMRK/utils/RMRKEquipRenderUtils.md, docs/RMRK/utils/RMRKNestableRenderUtils.md, test/renderUtils.ts
Adds new render utils:
- getEquippableSlotsFromParentForPendingChild
- getChildrenWithTopMetadata
- getPendingChildIndex
=> Render utils
