- contracts/RMRK/MultiResourceToken721.sol
- contracts/RMRK/MultiResourceTokenAbstract.sol
- contracts/mocks/MultiResourceToken721Mock.sol
- test/multiresource.ts
This is to avoid later duplication, when we create an implementation to include nesting and multiresource which must share ERC721 capabilities (ownership)
> Moves most of multirsource implementation to abstract class

- contracts/RMRK/RMRKEquippable.sol
- contracts/RMRK/RMRKNesting.sol
- contracts/RMRK/RMRKNestingMultiResource.sol
- contracts/RMRK/abstracts/ERC721Abstract.sol
- contracts/RMRK/abstracts/NestingAbstract.sol
- contracts/mocks/RMRKMultiResourceMock.sol
- contracts/mocks/RMRKNestingMock.sol
- contracts/mocks/RMRKNestingMultiResourceMock.sol
- test/multiresource.ts
- test/nesting.ts
I have continued with custom error updates, mostly in the NestingAbstract contract.
Also, I commented out hardhat/console.sol as I don't think we should commit it enabled and it's not used anywhere at the moment anyway.
> Update Nesting contracts with custom errors

- contracts/RMRK/RMRKEquippable.sol
- contracts/RMRK/RMRKMultiResource.sol
- contracts/RMRK/RMRKNestingMultiResource.sol
- contracts/RMRK/abstracts/MultiResourceAbstract.sol
- contracts/RMRK/interfaces/IRMRKMultiResource.sol
- contracts/RMRK/interfaces/IRMRKNestingWithEquippable.sol
- contracts/implementations/RMRKNestingImpl.sol
- contracts/mocks/RMRKNestingMock.sol
- test/behavior/equippableResources.ts
- test/behavior/equippableSlots.ts
- test/behavior/multiresource.ts
- test/behavior/nesting.ts
Resources now have independent approvals which apply to accepting, rejecting and setting priorities on resources.
On Equippables: equip, unequip and replace equip use the nesting permissions. For this a new method was added to the `IRMRKNestingWithEquippable` interface: `isApprovedOrOwner` so permissions can be fully checked with a single external call.
Tests for added for nesting, resources and resources on equippable for both approvals and approvals for all.
> Refactoring of approvals

- contracts/RMRK/RMRKEquippable.sol
- contracts/RMRK/RMRKMultiResource.sol
- contracts/RMRK/RMRKNesting.sol
- contracts/RMRK/RMRKNestingMultiResource.sol
- contracts/RMRK/RMRKNestingWithEquippable.sol
- contracts/RMRK/abstracts/MultiResourceAbstract.sol
- contracts/mocks/RMRKNestingWithEquippableMock.sol
- test/behavior/equippableResources.ts
- test/equippable.ts
- test/nestingMultiResource.ts
Resource approvals are cleaned after transfer or burn using a hook
The hook is implemented on RMRKNestingWithEquippable (new) and RMRKNestingMultiResource
Splits RMRKNestingMock into a simple one with INestingReceiver and RMRKNestingWithEquippableMock.
> Clean resource approvals on transfer and burn

- contracts/RMRK/RMRKEquippable.sol
- contracts/RMRK/RMRKNesting.sol
- contracts/RMRK/RMRKNestingWithEquippable.sol
- contracts/RMRK/interfaces/IRMRKEquippable.sol
- contracts/RMRK/interfaces/IRMRKNestingWithEquippable.sol
- test/behavior/equippableResources.ts
To  do so, the slot id must be sent from the equippable parent through all the calls
Also, the Nesting Parent must send it's equippable address to the Nesting child, (this could lie), which is then passed to the Equippable child for validation.
Even though the nesting parent can lie to the child, this could help prevent UI errors. Also, there's a known vulnerability in which a malicious nesting parent could force marking children as equipped or not even if the caller does not own the token.
> ChildEquippable.markEquipped now also checks if equip is valid

- contracts/RMRK/nesting/IRMRKNesting.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/implementations/RMRKEquippableImpl.sol
- contracts/implementations/RMRKNestingExternalEquipImpl.sol
- contracts/implementations/RMRKNestingImpl.sol
- contracts/implementations/RMRKNestingMultiResourceImpl.sol
- contracts/mocks/RMRKEquippableMock.sol
- contracts/mocks/RMRKNestingExternalEquipMock.sol
- contracts/mocks/RMRKNestingMock.sol
- contracts/mocks/RMRKNestingMultiResourceMock.sol
- test/behavior/nesting.ts
Internal _burn and external burnFromParent where doing exactly the same, with only slightly different rules on who could call them.
They are now one with the rule being:
1. If parent it's an NFT, only it can burn
2. Other wise, owner (user address) or approved can burn.
> Merges burn and burnFromParent on Nesting, solves TODO.

- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/equippable/RMRKExternalEquip.sol
- contracts/RMRK/equippable/RMRKNestingExternalEquip.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/RMRK/nesting/RMRKNestingMultiResource.sol
The problem:
When transfering a token with nested children, the children approvals are not updated, it would be very expensive to do so and malicious children may prevent it. This affects the regular approval and the approval for resources with the following vulnerability:
1. I approve a child token to a secondary address of mine
2. Sell the parent
3. I could do changes on resources for child (approved for resources)
4. If the child is later unnested, I could transfer it using the approved address.
Solution:
Instead of keeping track of approvals per token (token->approved), we add an extra level which is the approver. New mapping is token->approver->approved.
When checking if an address is approved, we check against the token Id and current owner, so if the root owner changes, permissions …
> Adds additional level on approvals

- contracts/RMRK/multiresource/AbstractMultiResource.sol
- contracts/RMRK/multiresource/IRMRKMultiResource.sol
- test/behavior/multiresource.ts
The purpose of this is to have a standard function which implements can override to include custom logic such as fallback and enumerated resources.
This would be the recommended method for marketplaces and similar to access resources.
> Adds MultiResource.getResourceMetaForToken(tokenId, resourceIndex)

- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/equippable/RMRKExternalEquip.sol
- contracts/RMRK/multiresource/AbstractMultiResource.sol
- contracts/RMRK/multiresource/IRMRKMultiResource.sol
- contracts/RMRK/utils/IRMRKMultiResourceRenderUtils.sol
- contracts/RMRK/utils/RMRKMultiResourceRenderUtils.sol
- test/behavior/equippableResources.ts
- test/behavior/multiresource.ts
- test/externalEquip.ts
- test/implementations/equippable.ts
- test/implementations/multiresource.ts
- test/multiresource.ts
- test/renderUtils.ts
Returning a Resource object with the redundant Id and the meta is not smart
It adds contract size, gas and makes it a bit harder for UI to use.
> Changes getResource for getResourceMeta

- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/equippable/RMRKExternalEquip.sol
- contracts/RMRK/equippable/RMRKNestingExternalEquip.sol
- contracts/RMRK/multiresource/AbstractMultiResource.sol
- contracts/RMRK/multiresource/IRMRKMultiResource.sol
- contracts/RMRK/multiresource/RMRKMultiResource.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/RMRK/nesting/RMRKNestingMultiResource.sol
- contracts/RMRK/utils/IRMRKMultiResourceRenderUtils.sol
- contracts/RMRK/utils/RMRKMultiResourceRenderUtils.sol
- test/behavior/equippableResources.ts
- test/behavior/multiresource.ts
- test/externalEquip.ts
- test/implementations/equippable.ts
- test/implementations/multiresource.ts
- test/multiresource.ts
- test/renderUtils.ts
This was done in the past but removed to make contracts easier to understand. We kind of regret.
The approvals for resources are not included on the Abstract since the implementation defers, on contracts using nesting approvals need to have 2 levels.
The only negative side effect from this is that code is slightly harder to understand, because part of the implementation is in another file, and some people might not be familiarized with the concept of an abstract class.
The good side is that we maintain a code of >200 lines in a single place instead of 4.
> Recreates AbstractMultiResource extracting duplicated code from 4 contracts

- contracts/RMRK/extension/typedMultiResource/IRMRKTypedMultiResource.sol
- contracts/RMRK/extension/typedMultiResource/RMRKNestingTypedMultiResource.sol
- contracts/RMRK/extension/typedMultiResource/RMRKTypedEquippable.sol
- contracts/RMRK/extension/typedMultiResource/RMRKTypedExternalEquippable.sol
- contracts/RMRK/extension/typedMultiResource/RMRKTypedMultiResource.sol
- contracts/RMRK/extension/typedMultiResource/RMRKTypedMultiResourceAbstract.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/mocks/extensions/RMRKNestingTypedMultiResourceMock.sol
- contracts/mocks/extensions/RMRKTypedEquippableMock.sol
- contracts/mocks/extensions/RMRKTypedExternalEquippableMock.sol
- contracts/mocks/extensions/RMRKTypedMultiResourceMock.sol
- test/extensions/typedMultiResource.ts
- test/nestingExternalEquip.ts
This interface forces the user to implement a `getResourceType` method.
There are 4 core implementations available for each of the combinations that inherits from IMultiresource. Also 4 corresponding mocks to test the basics.
On the `RMRKTypedMultiResourceMock` there's additionally a utility function implemented to show how this could be used to get the highest priority resource for a given token, filtering by type: `getTopResourceMetaForTokenWithType`.
> Adds IRMRKTypedMultiResource

- contracts/RMRK/nesting/RMRKNesting.sol
- test/behavior/nesting.ts
If you create an inheritance loop, ownership checks will always run out of gas due to an infinite loop. 
We avoid this at least up to 10 levels.
> Checks for inheritance loop, up to 100 levels of nesting.

- contracts/RMRK/core/RMRKCore.sol
- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/extension/soulbound/IRMRKSoulbound.sol
- contracts/RMRK/extension/soulbound/RMRKSoulbound.sol
- contracts/RMRK/multiresource/RMRKMultiResource.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/mocks/extensions/soulbound/RMRKSemiSoulboundNestingMock.sol
- contracts/mocks/extensions/soulbound/RMRKSoulboundEquippableMock.sol
- contracts/mocks/extensions/soulbound/RMRKSoulboundMultiResourceMock.sol
- contracts/mocks/extensions/soulbound/RMRKSoulboundNestingExternalEquippableMock.sol
- contracts/mocks/extensions/soulbound/RMRKSoulboundNestingMock.sol
- contracts/mocks/extensions/soulbound/RMRKSoulboundNestingMultiResourceMock.sol
- test/extensions/soulbound.ts
A single interface and abstract class.
Implementers can override the `isSoulbound` method for custom cases.
Adds mocks and tests for every lego combination.
> Implements Soulbound extension

- contracts/RMRK/nesting/RMRKNesting.sol
- test/behavior/nesting.ts
Additional, now to keep track of what children are active to avoid duplicates, we simply use an int flag. 
Previously we kept a position which was complex to keep up to date and provided no additional gain.
> Prevents from reclaiming a child which is still pending or active

- contracts/RMRK/equippable/RMRKNestingExternalEquip.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/implementations/RMRKNestingExternalEquipImpl.sol
I did a security pass of the contracts and I didn't find anything major.
I noticed an unused mapping `_owners` in the RMRKNesting contract which I removed.
I also have a suggestion for the split equippable to check for the support of the required interface in the `setEquippableAddress` function.
> Code review

- contracts/RMRK/access/OwnableLock.sol
- contracts/RMRK/base/RMRKBaseStorage.sol
- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/equippable/RMRKExternalEquip.sol
- contracts/RMRK/equippable/RMRKNestingExternalEquip.sol
- contracts/RMRK/extension/reclaimableChild/RMRKReclaimableChild.sol
- contracts/RMRK/extension/soulbound/RMRKSoulbound.sol
- contracts/RMRK/library/RMRKErrors.sol
- contracts/RMRK/multiresource/AbstractMultiResource.sol
- contracts/RMRK/multiresource/RMRKMultiResource.sol
- contracts/RMRK/nesting/RMRKNesting.sol
- contracts/RMRK/nesting/RMRKNestingMultiResource.sol
- contracts/RMRK/utils/RMRKEquipRenderUtils.sol
- contracts/RMRK/utils/RMRKMintingUtils.sol
- contracts/RMRK/utils/RMRKMultiResourceRenderUtils.sol
- contracts/implementations/RMRKEquippableImpl.sol
- contracts/implementations/RMRKExternalEquipImpl.sol
- contracts/implementations/RMRKMultiResourceImpl.sol
- contracts/implementations/RMRKNestingMultiResourceImpl.sol
- contracts/mocks/RMRKEquippableMock.sol
- contracts/mocks/RMRKExternalEquipMock.sol
- contracts/mocks/RMRKMultiResourceMock.sol
- contracts/mocks/RMRKNestingMultiResourceMock.sol
- test/behavior/equippableResources.ts
- test/behavior/multiresource.ts
- test/multiresource.ts
- test/nesting.ts
Errors were extractred to a library smart contract. The contract option was picked over the library simply because deployment in such manner should conserve gas. The errors library smart contracts was then imported in the smart contracts and the inheritance tree respected, so that each instance only gets it inherited once.
> Extract errors to a library

- README.md
- hardhat.config.ts
Landing README has been updated to acknowledge the namechange of the legos.
Ropsten network has been removed and the Görli network has replaced the references to it.
> Update landing README & remove Ropsten

- contracts/RMRK/extension/tokenProperties/IRMRKTokenProperties.sol
- contracts/RMRK/extension/tokenProperties/RMRKTokenProperties.sol
- contracts/mocks/extensions/tokenProperties/RMRKTokenPropertiesMock.sol
- docs/RMRK/extension/tokenProperties/RMRKTokenProperties.md
- docs/mocks/extensions/tokenProperties/RMRKTokenPropertiesMock.md
- test/extensions/tokenProperties.ts
Adds tests for duplicate keys, keys shared among different types and values shared among different string properties.
Caches string values to reduce gas when same value is used several times.
Splits minimal abstract implementation and mock to make it easier to extend.
> Improvements on token properties

- .github/CODEOWNERS
- .github/pull_request_template.md
The PR template wasn't loading as it should have been merged directly to master. I also added CODEOWNERS while I was at it.
> Fix pr template

- contracts/RMRK/access/Ownable.sol
- docs/RMRK/access/Ownable.md
- docs/RMRK/access/OwnableLock.md
- docs/RMRK/utils/RMRKMintingUtils.md
- docs/implementations/RMRKCatalogImpl.md
- docs/implementations/abstracts/RMRKAbstractEquippableImpl.md
- docs/implementations/abstracts/RMRKAbstractMultiAssetImpl.md
- docs/implementations/abstracts/RMRKAbstractNestableImpl.md
- docs/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.md
- docs/implementations/erc20Pay/RMRKEquippableImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKMultiAssetImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKNestableImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKNestableMultiAssetImplErc20Pay.md
- docs/implementations/nativeTokenPay/RMRKEquippableImpl.md
- docs/implementations/nativeTokenPay/RMRKExternalEquipImpl.md
- docs/implementations/nativeTokenPay/RMRKMultiAssetImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableExternalEquipImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableMultiAssetImpl.md
- docs/implementations/premint/RMRKEquippableImplPreMint.md
- docs/implementations/premint/RMRKMultiAssetImplPreMint.md
- docs/implementations/premint/RMRKNestableImplPreMint.md
- docs/implementations/premint/RMRKNestableMultiAssetImplPreMint.md
- docs/mocks/MintingUtilsMock.md
- docs/mocks/OwnableLockMock.md
- test/implementations/abstracts.ts
- test/implementations/catalog.ts
- test/implementations/externalEquippable.ts
- test/mintingUtils.ts
An event denoting `contributor` status change was added.
In order to preserve space a single event was added that includes a flag denoting whether the role was granted or revoked:
```solidity
event ContributorUpdate(address indexed contributor, bool isContributor);
```
Other actions:
- Added documentation comments to `OwnershipTransferred`
- Documented `ContributorUpdate`
- Add the event to relevant functions
- Add test examples verifying correct emission of the event
- Add test examples verifying correct emission of `OwnershipTransferred`
> Add event for contributor management

- contracts/RMRK/catalog/RMRKCatalog.sol
Adds internal methods to set catalog metadata and type.
- add `_setMetadataURI`
- add `_setType`
> Adds internal methods to set catalog metadata and type.

- contracts/RMRK/extension/multiAssetAutoIndex/IRMRKMultiAssetAutoIndex.sol
- contracts/RMRK/extension/multiAssetAutoIndex/RMRKMultiAssetAutoIndex.sol
- contracts/mocks/RMRKMultiAssetAutoIndexMock.sol
- test/extensions/multiAssetAutoIndex.ts
- test/interfaces.ts
- test/multiAssetAutoIndex.ts
This extension allow the user to call MultiAsset function without the help of an index.
For this feature I've create a new interface and its implementation along with a Mock contract and a test file:
- IRMRKMultiAssetAutoIndex.sol (interface)
- RMRKMultiAssetAutoIndex.sol (implementation)
- RMRKMultiAssetAutoIndexMock.sol (Mock)
- multiAssetAutoIndex.ts (testing)
> MultiAssetAutoIndex extension

- contracts/RMRK/utils/RMRKBulkWriterPerCollection.sol
- docs/RMRK/utils/RMRKBulkWriterPerCollection.md
- test/bulkWriter.ts
- test/kanariaUtils.ts
- test/renderUtils.ts
This contract is meant to exist 1 per NFT collection, the idea is to limit danger if the contract is somehow compromised. That however makes UX worse, since we need to deploy one per collection and users need to approve it too.
It's up for discussion
- Implements replace equip
- Implements bulk equip
> Implements BulkWriterPerCollection contract.

- contracts/RMRK/catalog/IRMRKCatalog.sol
- contracts/RMRK/catalog/RMRKCatalog.sol
- contracts/RMRK/equippable/IRMRKEquippable.sol
- contracts/RMRK/equippable/RMRKEquippable.sol
- contracts/RMRK/equippable/RMRKExternalEquip.sol
- contracts/implementations/abstracts/RMRKAbstractEquippableImpl.sol
- contracts/implementations/nativeTokenPay/RMRKExternalEquipImpl.sol
Any use case which builds the list of parts with code will be blocked otherwise, since this happens in the core implementation and all variables are private. The only workaround would be to modify the installed package which is a really bad practice.
> Uses memory parameters instead of calldata to receive partIds

- contracts/RMRK/nestable/RMRKNestable.sol
In few cases, the events where being triggered after the hook which is not a great practice and was not consistent with the rest of the code
> Emits events before the hooks.

- contracts/RMRK/extension/RMRKRoyalties.sol
- contracts/RMRK/library/RMRKErrors.sol
- docs/RMRK/extension/RMRKRoyalties.md
- docs/implementations/abstracts/RMRKAbstractEquippableImpl.md
- docs/implementations/abstracts/RMRKAbstractMultiAssetImpl.md
- docs/implementations/abstracts/RMRKAbstractNestableImpl.md
- docs/implementations/abstracts/RMRKAbstractNestableMultiAssetImpl.md
- docs/implementations/erc20Pay/RMRKEquippableImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKMultiAssetImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKNestableImplErc20Pay.md
- docs/implementations/erc20Pay/RMRKNestableMultiAssetImplErc20Pay.md
- docs/implementations/nativeTokenPay/RMRKEquippableImpl.md
- docs/implementations/nativeTokenPay/RMRKMultiAssetImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableExternalEquipImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableImpl.md
- docs/implementations/nativeTokenPay/RMRKNestableMultiAssetImpl.md
- docs/implementations/premint/RMRKEquippableImplPreMint.md
- docs/implementations/premint/RMRKMultiAssetImplPreMint.md
- docs/implementations/premint/RMRKNestableImplPreMint.md
- docs/implementations/premint/RMRKNestableMultiAssetImplPreMint.md
Prevents deploying a contract with royalties over 100%
Also changes the getters from external to public.
> Royalties checks and improvements

- contracts/RMRK/equippable/RMRKMinifiedEquippable.sol
- contracts/mocks/RMRKMinifiedEquippableMock.sol
- docs/RMRK/equippable/RMRKMinifiedEquippable.md
- docs/mocks/RMRKMinifiedEquippableMock.md
- test/minifiedEquippable.ts
This was supposed to include [this commit](https://github.com/rmrk-team/evm/commit/0a46876ad03a568bdc3fe3cda0f2bfbafe976d10) where I add a "minified" equippable core implementation. It simply merges the implementations of MA, Nestable and Equippable and removes intermediate steps and no longer necessary overrides. The code is mostly duplicated but I think it's a fair price at this point that the code is so stable. It does not include any extension or library code since after testing each it proved to not help with the size at all, in some cases it even increased it.
The ready to use implementations for equippable now inherit from this version, which saves 0.184 of size using 200 runs.
This PR includes a new mock and test suit for it, going trough all behaviors for MA, Nestable, Equippable …
> Minified equippable tests

- contracts/RMRK/utils/RMRKEquipRenderUtils.sol
- docs/RMRK/utils/RMRKEquipRenderUtils.md
- test/renderUtils.ts
Adds util to get information about the current children equipped into a specific parent and asset:
`RMRKEquipRenderUtils.equippedChildrenOf`
> Adds Equip render Utils: equippedChildrenOf

- contracts/RMRK/extension/emotable/IRMRKEmoteTracker.sol
- contracts/RMRK/extension/emotable/RMRKEmoteTracker.sol
- docs/RMRK/extension/emotable/IRMRKEmoteTracker.md
- docs/RMRK/extension/emotable/RMRKEmoteTracker.md
- docs/mocks/extensions/emotable/RMRKEmoteTrackerMock.md
- test/extensions/emotable.ts
We agreed that the `hasEmoterUsedEmote` should return `bool`, but it was returning `uint256`. This PR fixes the issue.
Changed the return type to ` bool`.
> Change return type in EmoteTracker

- test/behavior/erc721.ts
- test/externalEquip.ts
- test/multiasset.ts
Makes sure when checking for events that the `await` is behind the `expect`
> Fixes checking of events in some cases.

- contracts/implementations/nativeTokenPay/RMRKEquippableImpl.sol
- contracts/implementations/nativeTokenPay/RMRKMultiAssetImpl.sol
- contracts/implementations/nativeTokenPay/RMRKNestableExternalEquipImpl.sol
- contracts/implementations/nativeTokenPay/RMRKNestableImpl.sol
- contracts/implementations/nativeTokenPay/RMRKNestableMultiAssetImpl.sol
- test/behavior/mintingImpl.ts
- test/implementations/lazyMintNativeTokenPay.ts
- test/implementations/multiasset.ts
Error raises also if value is higher so it was misleading.
> Renames RMRKMintUnderpriced error to RMRKWrongValueSent
